### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by RepeatSoftware** [joelpob/betfairng#17]
Hi.  Just downloaded the zip and extracted.  Getting a ton of messages like:
Error	CS2001	Source file 'C:\Repeat\betfairng-master\stream-api-sample-code\csharp\Betfair.ESAClient\Betfair.ESASwagger\Betfair\ESASwagger\Model\AllRequestTypesExample.cs' could not be found.	Betfair.ESASwagger	C:\Repeat\betfairng-master\CSC	1	Active

Have searched for AllRequestTypesExample.cs but cannot find the file.  

Thanks

Mark.

**Comment by joelpob** [comment]
You're missing the submodule repo (the Betfair provided example code) which is used by the main repo. Instead of downloading the zip, clone the repo and the submodule (last two commands are most important):

git clone https://github.com/joelpob/betfairng
cd betfairng
git submodule init
git submodule update
